export const userFile = {
  email: "",
  firstName: "",
  middleName: "",
  lastName: "",
  causeOfNicuAdmission: "",
  birthDate: "",
  birthWeight: "",
  governorate: "",
  city: "",
  village: "",
  street: "",
  phoneNumber: "",
  phoneNumber1: "",
  gender: "male",
  password: "",
  createdAt: "",
  labourProblems: "",
  headCircumferance: "",
  congenitalAnomalies: "",
  role: "Patient",
  pastHistoryOfDisease: "",
  pastHistoryOfOperation: "",
  notes: "",
};
