import {governorates} from './governorates-list'
export const userFile = {
  email: "",
  firstName: "",
  middleName: "",
  lastName: "",
  causeOfNicuAdmission: "",
  birthDate:null,
  birthWeight: "",
  governorate: governorates.at(0).value,
  city: "",
  village: "",
  street: "",
  phoneNumber: null,
  phoneNumber1: null,
  gender: "male",
  password: "",
  labourProblems: "",
  headCircumferance: "",
  congenitalAnomalies: "",
  role: "Patient",
  pastHistoryOfDisease: "",
  pastHistoryOfOperation: "",
  notes: "",
};
